import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Cal_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

const calSans = Cal_Sans({
  variable: "--font-calSans",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "xVS Attendance App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: "/android-chrome-192x192.png",
    apple: [
      {
        url: "/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "xVS Attendance App",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${calSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-106.25 mx-auto">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
